### ISSUE TITLE
Depends unmaintained library

### ISSUE THREAD

**Issue by OhadRau** [sh4869/twitter.dart#11]
This library depends on oauth.dart, which uses the unmaintained cipher library. The version of BigNum that Cipher depends on no longer compiles under the latest version of Dart. Some other Oauth libraries are available (such as the oauth2 package and flutteroauth, https://github.com/dart-lang/oauth2 and https://github.com/hitherejoe/FlutterOAuth respectively).  Since it looks like oauth.dart isn't frequently maintained, I think the best solution is to switch to another Oauth library.

**Comment by sh4869** [comment]
Twitter API does not correspond OAuth2, So I cannot use dart-team's oauth2 library.  There is only oauth.dart that OAuth **1** Dart library.
