### ISSUE TITLE
Unable to post status using rest API

### ISSUE THREAD

**Issue by RandyStevens** [sh4869/twitter.dart#7]
above the screenshot here is my APIkey and stuff like in the exmample Folder
<img width="641" alt="screen shot 2018-03-04 at 1 26 59 am" src="https://user-images.githubusercontent.com/25543498/36944266-5a1fc24a-1f4d-11e8-92bd-a1259d04a016.png">

![screen shot 2018-03-04 at 1 42 27 am](https://user-images.githubusercontent.com/25543498/36944272-656a92d8-1f4d-11e8-97bb-ee05359d934b.png)

**Comment by sh4869** [comment]
You should pass a body for request and use await keyword.

```
var a = await twitter.request("POST","statuses/update.json",body: body);
```

**Comment by sh4869** [comment]
You should pass a body parameter.

```
var a = twitter.request("POST", "statuses/update.json",body: {"status":"test"});
a.then((value){
    new File("test.json").writeAsString(value.body);
});
```

**Comment by RandyStevens** [comment]
Excellent thank you!
