### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by ShawnRG** [sh4869/twitter.dart#8]
Calling `var responses =  await twitter.request("GET", "statuses/home_timeline.json");`

<details>
<summary>Log</summary>

```
E/flutter ( 4441): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 4441): Bad Request
E/flutter ( 4441): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
E/flutter ( 4441): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 4441): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

</details>

**Comment by sh4869** [comment]
maybe it is error response on Twitter API. You'd check the API keys.

ref: https://developer.twitter.com/en/docs/basics/response-codes

**Comment by ShawnRG** [comment]
I have resolved the error. I had left in a leading space in one of the keys. But a new issue appeared but as its not related to this repo i have opened an issue on flutter:
https://github.com/flutter/flutter/issues/16337
